name: Set cron schedule
description: "Set the cron schedule for a GitHub Action"
branding:
  icon: "clock"
  color: purple
inputs:
  token:
    description: 'Personal access token with "workflow" scope'
    required: true
  cron:
    description: "cron schedule expression (UTC Timezone). Set multiple schedules by separating by line breaks"
    required: true
  workflow:
    description: "ID or filename of workflow to be updated. Defaults to the current workflow."
    required: false
  message:
    description: 'Commit message. You can use $WORKFLOW_NAME and $CRON_SCHEDULE placeholders. Defaults to "ci($WORKFLOW_NAME): update cron schedule: $CRON_EXPRESSIONS"'
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
